version: '3.7'
services:
  frontend:
    build: .
    ports:
      - "8099:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      VUE_APP_BACKEND_URL: http://192.168.10.51:3900